//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Resources.Views.Review {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateOrUpdate {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrUpdate() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppWeb.Resources.Views.Review.CreateOrUpdate", typeof(CreateOrUpdate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Status_Review_ {
            get {
                return ResourceManager.GetString("Status Review:", resourceCulture);
            }
        }
        
        internal static string Product_ {
            get {
                return ResourceManager.GetString("Product:", resourceCulture);
            }
        }
        
        internal static string Product_Name_ {
            get {
                return ResourceManager.GetString("Product Name:", resourceCulture);
            }
        }
        
        internal static string Title_ {
            get {
                return ResourceManager.GetString("Title:", resourceCulture);
            }
        }
        
        internal static string Tags_ {
            get {
                return ResourceManager.GetString("Tags:", resourceCulture);
            }
        }
        
        internal static string Content_ {
            get {
                return ResourceManager.GetString("Content:", resourceCulture);
            }
        }
        
        internal static string Author_Assessment_ {
            get {
                return ResourceManager.GetString("Author Assessment:", resourceCulture);
            }
        }
    }
}
