//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Resources.Views.User {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetUser {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetUser() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppWeb.Resources.Views.User.GetUser", typeof(GetUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Admin_User {
            get {
                return ResourceManager.GetString("Admin User", resourceCulture);
            }
        }
        
        internal static string Get_User_Reviews {
            get {
                return ResourceManager.GetString("Get User Reviews", resourceCulture);
            }
        }
        
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        internal static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        internal static string ReviewsLikes {
            get {
                return ResourceManager.GetString("ReviewsLikes", resourceCulture);
            }
        }
        
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        internal static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        internal static string Social_Email {
            get {
                return ResourceManager.GetString("Social_Email", resourceCulture);
            }
        }
        
        internal static string Social_Network {
            get {
                return ResourceManager.GetString("Social_Network", resourceCulture);
            }
        }
        
        internal static string Social_FirstName {
            get {
                return ResourceManager.GetString("Social_FirstName", resourceCulture);
            }
        }
        
        internal static string Social_LastName {
            get {
                return ResourceManager.GetString("Social_LastName", resourceCulture);
            }
        }
        
        internal static string Comment_Count {
            get {
                return ResourceManager.GetString("Comment.Count", resourceCulture);
            }
        }
        
        internal static string Review_Count {
            get {
                return ResourceManager.GetString("Review.Count", resourceCulture);
            }
        }
        
        internal static string Update_User {
            get {
                return ResourceManager.GetString("Update User", resourceCulture);
            }
        }
    }
}
