//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Resources.Views.User {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetUserReviews {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetUserReviews() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppWeb.Resources.Views.User.GetUserReviews", typeof(GetUserReviews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string User_Reviews {
            get {
                return ResourceManager.GetString("User Reviews", resourceCulture);
            }
        }
        
        internal static string Create_Review {
            get {
                return ResourceManager.GetString("Create Review", resourceCulture);
            }
        }
        
        internal static string Click_the_headers_to_sort_the_table_ {
            get {
                return ResourceManager.GetString("Click the headers to sort the table.", resourceCulture);
            }
        }
        
        internal static string First_click__the_sorting_is_ascending__A_to_Z___Click_again__the_sorting_will_be_descending__Z_to_A__ {
            get {
                return ResourceManager.GetString("First click, the sorting is ascending (A to Z). Click again, the sorting will be " +
                        "descending (Z to A).", resourceCulture);
            }
        }
        
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        internal static string Redaction {
            get {
                return ResourceManager.GetString("Redaction", resourceCulture);
            }
        }
        
        internal static string Author_Assessment {
            get {
                return ResourceManager.GetString("Author Assessment", resourceCulture);
            }
        }
        
        internal static string User_Assessment {
            get {
                return ResourceManager.GetString("User Assessment", resourceCulture);
            }
        }
        
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        internal static string RedactionDate {
            get {
                return ResourceManager.GetString("RedactionDate", resourceCulture);
            }
        }
        
        internal static string AuthorAssessment {
            get {
                return ResourceManager.GetString("AuthorAssessment", resourceCulture);
            }
        }
        
        internal static string AverageUserRating {
            get {
                return ResourceManager.GetString("AverageUserRating", resourceCulture);
            }
        }
    }
}
